### ISSUE TITLE
screen shots

### ISSUE THREAD

**Issue by adriatic** [adriatic/items#2]
<p align=center>
  <img src="https://user-images.githubusercontent.com/2712405/38224186-d8c6ce6e-36bc-11e8-9cbe-b8adcc493ffb.png"></img>
 <br>Image 4
</p>

![image]()

<p align=center>
  <img src=""></img>
 <br>
</p>

**Comment by adriatic** [comment]
```
TypeError: Path must be a string. Received [ 'C:\\work\\tests\\Monterey-testing-08302016' ]
    at assertPath (path.js:7:11)
    at join (path.js:466:7)
    at Object.join (file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/monterey-framework/monterey-pal-electron@0.1.43/fs.js:231:22)
    at ProjectName.<anonymous> (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:53:42)
    at next (<anonymous>)
    at file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:16:65
    at __awaiter (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:12:12)
    at ProjectName.checkFolderExistence (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:50:16)
    at ProjectName.attached (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:43:14)
    at Controller.attached (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.0/aurelia-templating.js:3471:24)
```

**Comment by adriatic** [comment]
<p align=center>
  <img src=""></img>
 <br><br>
Image 1
</p>
